version: '2'

services:
  postgres:
    image: postgres:11.6
    env_file: 
      - ./env/db.env
  resource_manager:
    restart: always
    env_file: 
      - ./env/db.env
      - ./env/services.env
    environment:
      - DJANGO_SECRET_KEY=local
    image: resource_manager
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               python ./manage.py makemigrations &&
               python ./manage.py migrate &&
               python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    # networks:
    #   - custom-net
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"

# networks: 
#   custom-net:
#     driver: bridge